const FALLBACK_PRODUCTS = [
  {
    id: 1,
    nom: "Snail 96 Mucin Essence",
    narx: 145000,
    teglari: ["serum"],
    emoji: "🐌",
    grad: "linear-gradient(135deg, #f5f5dc, #d2b48c)",
    hajm: "100ml",
    tarkib: "96% Snail Secretion Filtrate, Betaine, Butylene Glycol",
    qollanish: "Tozalangan yuzga toneridan keyin surting."
  },
  {
    id: 2,
    nom: "Low pH Good Morning Gel Cleanser",
    narx: 95000,
    teglari: ["tozalash"],
    emoji: "☀️",
    grad: "linear-gradient(135deg, #fffacd, #ffd700)",
    hajm: "150ml",
    tarkib: "Tea Tree Oil, BHA (Betaine Salicylate)",
    qollanish: "Ertalab va kechqurun nam yuzga surtib, yuving."
  },
  {
    id: 3,
    nom: "AHA/BHA Clarifying Treatment Toner",
    narx: 110000,
    teglari: ["toner"],
    emoji: "🧪",
    grad: "linear-gradient(135deg, #e0ffff, #afeeee)",
    hajm: "150ml",
    tarkib: "Salix Alba (Willow) Bark Water, Pyrus Malus (Apple) Fruit Water",
    qollanish: "Paxta yordamida yuzga surting."
  },
  {
    id: 4,
    nom: "Advanced Snail 92 All In One Cream",
    narx: 160000,
    teglari: ["krem"],
    emoji: "🐚",
    grad: "linear-gradient(135deg, #fffaf0, #f5f5dc)",
    hajm: "100g",
    tarkib: "92% Snail Secretion Filtrate, Adenosine",
    qollanish: "Parvarishning oxirgi bosqichida surting."
  },
  {
    id: 5,
    nom: "Birch Juice Moisturizing Sunscreen",
    narx: 190000,
    teglari: ["quyosh"],
    emoji: "🌳",
    grad: "linear-gradient(135deg, #f0f8ff, #add8e6)",
    hajm: "50ml",
    tarkib: "Birch Sap, Hyaluronic Acid, Niacinamide",
    qollanish: "Ko'chaga chiqishdan 20 daqiqa oldin surting."
  },
  {
    id: 6,
    nom: "Lip Sleeping Mask Berry",
    narx: 140000,
    teglari: ["lab", "maska"],
    emoji: "🍓",
    grad: "linear-gradient(135deg, #fff0f5, #ffb6c1)",
    hajm: "20g",
    tarkib: "Berry Mix Complex, Vitamin C",
    qollanish: "Uxlashdan oldin labga qalin qilib surting."
  },
  {
    id: 7,
    nom: "Rice Mask Wash Off",
    narx: 125000,
    teglari: ["maska"],
    emoji: "🌾",
    grad: "linear-gradient(135deg, #fdf5e6, #faf0e6)",
    hajm: "100g",
    tarkib: "Rice Bran Water, Rice Flour",
    qollanish: "Yuzga surtib, 10-15 daqiqadan keyin yuving."
  },
  {
    id: 8,
    nom: "Centella Ampoule",
    narx: 175000,
    teglari: ["serum"],
    emoji: "🌿",
    grad: "linear-gradient(135deg, #f0fff0, #98fb98)",
    hajm: "100ml",
    tarkib: "100% Centella Asiatica Extract",
    qollanish: "Tinchlantirish uchun yuzga bir necha tomchi surting."
  },
  {
    id: 9,
    nom: "Dokdo Toner",
    narx: 119000,
    teglari: ["toner"],
    emoji: "🌊",
    grad: "linear-gradient(135deg, #f0f8ff, #e0ffff)",
    hajm: "200ml",
    tarkib: "Deep Sea Water, Panthenol, Allantoin",
    qollanish: "Yuzni tozalagandan keyin foydalaning."
  },
  {
    id: 10,
    nom: "Green Tea Seed Serum",
    narx: 185000,
    teglari: ["serum"],
    emoji: "🍃",
    grad: "linear-gradient(135deg, #f5fffa, #90ee90)",
    hajm: "80ml",
    tarkib: "Green Tea Seed Oil, Panthenol",
    qollanish: "Namlikni saqlash uchun yuzga surting."
  },
  {
    id: 11,
    nom: "Vitamin C 23 Serum",
    narx: 155000,
    teglari: ["serum"],
    emoji: "🍊",
    grad: "linear-gradient(135deg, #fff5e6, #ffcc80)",
    hajm: "20ml",
    tarkib: "23% Pure Vitamin C, Vitamin E",
    qollanish: "Kechqurun yuzga surting, kunduzi SPF ishlating."
  },
  {
    id: 12,
    nom: "Heartleaf 77% Soothing Toner",
    narx: 165000,
    teglari: ["toner"],
    emoji: "🤍",
    grad: "linear-gradient(135deg, #ffffff, #f5f5f5)",
    hajm: "250ml",
    tarkib: "77% Heartleaf Extract, Betaine",
    qollanish: "Yallig'lanishni kamaytirish uchun surting."
  },
  {
    id: 13,
    nom: "BHA Blackhead Power Liquid",
    narx: 135000,
    teglari: ["serum", "tozalash"],
    emoji: "🌑",
    grad: "linear-gradient(135deg, #f5f5f5, #d3d3d3)",
    hajm: "100ml",
    tarkib: "4% Betaine Salicylate, Niacinamide",
    qollanish: "Haftada 2-3 marta qora nuqtalarga surting."
  },
  {
    id: 14,
    nom: "Hyaluronic Acid Watery Sun Gel",
    narx: 180000,
    teglari: ["quyosh"],
    emoji: "💧",
    grad: "linear-gradient(135deg, #e0f7fa, #81d4fa)",
    hajm: "50ml",
    tarkib: "8 types of Hyaluronic Acid, Astaxanthin",
    qollanish: "Quyoshdan himoya uchun har kuni surting."
  },
  {
    id: 15,
    nom: "Oil-Free Ultra-Moisturizing Lotion",
    narx: 145000,
    teglari: ["krem"],
    emoji: "🧴",
    grad: "linear-gradient(135deg, #fdfcf0, #f1f8e9)",
    hajm: "100ml",
    tarkib: "70% Birch Sap, Tea Tree Oil",
    qollanish: "Yog'li teri uchun namlantiruvchi sifatida surting."
  },
  {
    id: 16,
    nom: "Black Sugar Mask Wash Off",
    narx: 120000,
    teglari: ["maska"],
    emoji: "🍩",
    grad: "linear-gradient(135deg, #efebe9, #d7ccc8)",
    hajm: "100g",
    tarkib: "Black Sugar, Shea Butter",
    qollanish: "Skrab sifatida surtib, 10 daqiqadan keyin yuving."
  },
  {
    id: 17,
    nom: "Propolis Vitamin Synergy Serum",
    narx: 150000,
    teglari: ["serum"],
    emoji: "🐝",
    grad: "linear-gradient(135deg, #fffde7, #fff59d)",
    hajm: "50ml",
    tarkib: "70% Propolis, 12% Sea Buckthorn",
    qollanish: "Yuzga yorqinlik berish uchun surting."
  },
  {
    id: 18,
    nom: "Aloe Soothing Sun Cream",
    narx: 115000,
    teglari: ["quyosh"],
    emoji: "🌵",
    grad: "linear-gradient(135deg, #f1f8e9, #c5e1a5)",
    hajm: "50ml",
    tarkib: "Aloe Arborescens Leaf Extract",
    qollanish: "Namlantiruvchi quyosh kremi sifatida surting."
  },
  {
    id: 19,
    nom: "Galactomyces 95 Tone Balancing Essence",
    narx: 140000,
    teglari: ["serum"],
    emoji: "✨",
    grad: "linear-gradient(135deg, #fafafa, #eeeeee)",
    hajm: "100ml",
    tarkib: "95% Galactomyces Ferment Filtrate, Niacinamide",
    qollanish: "Yuz rangini tekislash uchun surting."
  },
  {
    id: 20,
    nom: "Honey Mask",
    narx: 195000,
    teglari: ["maska"],
    emoji: "🍯",
    grad: "linear-gradient(135deg, #fff8e1, #ffecb3)",
    hajm: "120g",
    tarkib: "38.7% Natural Honey",
    qollanish: "Yuzga surtib, 30 daqiqadan keyin yuving."
  },
  {
    id: 21,
    nom: "Mugwort Essence",
    narx: 180000,
    teglari: ["serum"],
    emoji: "🌿",
    grad: "linear-gradient(135deg, #f1f8e9, #dcedc8)",
    hajm: "160ml",
    tarkib: "100% Mugwort Extract",
    qollanish: "Tinchlantirish va detoks uchun surting."
  },
  {
    id: 22,
    nom: "Water Sleeping Mask",
    narx: 230000,
    teglari: ["maska"],
    emoji: "💧",
    grad: "linear-gradient(135deg, #e1f5fe, #b3e5fc)",
    hajm: "70ml",
    tarkib: "Hydro Ionized Mineral Water, Sleep-tox",
    qollanish: "Kechasi uxlashdan oldin surting."
  },
  {
    id: 23,
    nom: "Ginseng Essence Water",
    narx: 170000,
    teglari: ["toner"],
    emoji: "🪵",
    grad: "linear-gradient(135deg, #efebe9, #d7ccc8)",
    hajm: "150ml",
    tarkib: "80% Ginseng Root Water, Niacinamide",
    qollanish: "Yuzga quvvat berish uchun surting."
  },
  {
    id: 24,
    nom: "Dynasty Cream",
    narx: 185000,
    teglari: ["krem"],
    emoji: "👑",
    grad: "linear-gradient(135deg, #fdfcf0, #f5f5f5)",
    hajm: "50ml",
    tarkib: "Rice Bran Water, Ginseng Root Water, Squalane",
    qollanish: "Chuqur namlantirish uchun surting."
  },
  {
    id: 25,
    nom: "Beauty of Joseon Relief Sun",
    narx: 175000,
    teglari: ["quyosh"],
    emoji: "☀️",
    grad: "linear-gradient(135deg, #fffde7, #fff9c4)",
    hajm: "50ml",
    tarkib: "30% Rice Extract, Grain Probiotics",
    qollanish: "Kundalik quyoshdan himoya uchun surting."
  },
  {
    id: 26,
    nom: "Gua Sha Facial Tool",
    narx: 85000,
    teglari: ["aksessuar"],
    emoji: "💎",
    grad: "linear-gradient(135deg, #f3e5f5, #e1bee7)",
    hajm: "1 dona",
    tarkib: "Natural Rose Quartz / Jade",
    qollanish: "Yuz massaji uchun moy bilan ishlating."
  },
  {
    id: 27,
    nom: "Cotton Pads (Premium)",
    narx: 35000,
    teglari: ["aksessuar"],
    emoji: "☁️",
    grad: "linear-gradient(135deg, #ffffff, #f5f5f5)",
    hajm: "80 dona",
    tarkib: "100% Pure Cotton",
    qollanish: "Toner yoki makiyajni tozalash uchun."
  },
  {
    id: 28,
    nom: "Headband for Skincare",
    narx: 25000,
    teglari: ["aksessuar"],
    emoji: "🎀",
    grad: "linear-gradient(135deg, #fce4ec, #f8bbd0)",
    hajm: "1 dona",
    tarkib: "Soft Microfiber",
    qollanish: "Yuz yuvishda sochni ushlab turish uchun."
  }
];
