-- QoraQosh — boshlang'ich katalog (28 ta haqiqiy Koreya mahsuloti)
-- 001_schema.sql dan KEYIN ishga tushiring.
-- Narx va tannarxni admin panelidan yangilaysiz; bu yerda boshlang'ich qiymat.

insert into public.categories (slug, name, emoji, sort) values
  ('tozalash',  'Tozalash',        '🫧', 10),
  ('toner',     'Toner',           '💧', 20),
  ('serum',     'Serum',           '🧪', 30),
  ('krem',      'Krem',            '🫙', 40),
  ('niqob',     'Niqob',           '🎭', 50),
  ('quyosh',    'SPF himoya',      '☀️', 60),
  ('lab',       'Lab parvarishi',  '💋', 70),
  ('toplam',    'To''plam',         '🎁', 80)
on conflict (slug) do nothing;

insert into public.products
  (name, brand, category_id, step, price, cost_price, stock, volume, country,
   description, usage_text, ingredients, actives, concerns, skin_types, emoji, gradient)
select v.name, v.brand, c.id, v.step, v.price, v.cost_price, v.stock, v.volume, 'KR',
       v.description, v.usage_text, v.ingredients, v.actives, v.concerns, v.skin_types,
       v.emoji, v.gradient
from (values
-- ---------- TOZALASH ----------
('Low pH Good Morning Gel Cleanser','COSRX','tozalash','tozalash',89000,52000,30,'150 ml',
 'Terining tabiiy pH darajasini buzmaydigan yumshoq gel yuvish vositasi. Ertalabki tozalash uchun.',
 'Namlangan yuzga surtib, 1 daqiqa aylanma harakat bilan uqalang va iliq suvda yuving.',
 'Choy daraxti yog''i, 0.5% BHA (Betaine Salicylate), allantoin',
 array['bha','choy daraxti','allantoin'], array['yoglilik','teshik','sezgirlik'], array['yogli','aralash','sezgir'],'🫧', array['#1a2a3a','#2d5a6b']),
('Green Tea Foam Cleanser','Innisfree','tozalash','tozalash',75000,44000,30,'150 ml',
 'Jeju yashil choyi asosidagi ko''pikli yuvish vositasi. Yog'' muvozanatini tiklaydi.',
 'Kaftda ko''pirtiring, yuzga surting, 30 soniya uqalab yuving.',
 'Jeju yashil choy ekstrakti (16 aminokislota), glitserin',
 array['yashil choy','glitserin'], array['yoglilik','xiralik'], array['yogli','aralash','normal'],'🍵', array['#14301f','#2e6b45']),
('A.C Control Cleansing Foam','Some By Mi','tozalash','tozalash',82000,48000,25,'100 ml',
 'AHA-BHA-PHA kislotalari bilan akneli teriga mo''ljallangan tozalagich.',
 'Aknega moyil sohalarga alohida e''tibor berib yuving. Kuniga 1-2 marta.',
 'AHA, BHA, PHA kislotalari, Truecica kompleksi, choy daraxti',
 array['aha','bha','pha','centella'], array['akne','yoglilik','teshik'], array['yogli','aralash'],'🌿', array['#1c2b1a','#4a6b2d']),
('Super Aqua Ultra Hyaluron Cleansing Oil','Missha','tozalash','tozalash',118000,70000,20,'150 ml',
 'Pardoz va SPF ni eritib tozalaydigan gidrofil moy. Quruq teriga tortmaydi.',
 'QURUQ yuzga surtib pardozni eriting, suv qo''shib emulsiyaga aylantiring, yuving.',
 '10 xil gialuron kislotasi kompleksi, jojoba va kungaboqar yog''i',
 array['gialuron','jojoba'], array['quruqlik'], array['quruq','normal','aralash'],'💦', array['#152238','#2d4a7a']),
('Heartleaf Pore Deep Cleansing Oil','Anua','tozalash','tozalash',135000,80000,20,'200 ml',
 'Qora nuqta va tiqilgan teshiklarni ochadigan mashhur gidrofil moy.',
 'Quruq yuzda qora nuqtalar ustida 1 daqiqa uqalang, emulsiyaga aylantirib yuving.',
 'Houttuynia Cordata (Heartleaf) ekstrakti, o''simlik moylari',
 array['heartleaf'], array['teshik','akne','sezgirlik'], array['yogli','aralash','sezgir'],'🖤', array['#1a1a22','#3d3d52']),
-- ---------- TONER ----------
('AHA BHA PHA 30 Days Miracle Toner','Some By Mi','toner','toner',125000,74000,25,'150 ml',
 'Uch xil kislota bilan o''lik hujayralarni eritadi, aknedan keyingi izlarni ochadi.',
 'Paxta diskiga tomizib yuzni artib chiqing. Kechqurun boshlang, haftasiga 3 martadan.',
 'AHA, BHA, PHA, niatsinamid 2%, choy daraxti 10 000 ppm',
 array['aha','bha','pha','niatsinamid'], array['akne','teshik','dog','yoglilik'], array['yogli','aralash'],'🧴', array['#221a2e','#5a3d6b']),
('Green Tea Seed Skin','Innisfree','toner','toner',110000,65000,25,'160 ml',
 'Yengil namlantiruvchi toner, keyingi bosqichlarni yaxshi singdiradi.',
 'Yuvinishdan so''ng kaftga olib, yuzga yengil urib singdiring.',
 'Green Tea Biome, 5 xil gialuron kislotasi, pantenol',
 array['yashil choy','gialuron','pantenol'], array['quruqlik','sezgirlik'], array['normal','aralash','sezgir'],'🌱', array['#12281a','#3d7a4f']),
('Glow Deep Serum Toner','Beauty of Joseon','toner','toner',128000,76000,25,'150 ml',
 'Guruch suvi va arbutin bilan rangni tenglashtiruvchi toner-serum.',
 'Dog'' va rang xiraligiga qarshi ertalab-kechqurun surting.',
 'Guruch kepagi suvi 68%, arbutin 2%, pantenol',
 array['arbutin','guruch','pantenol'], array['dog','xiralik'], array['normal','quruq','aralash'],'🌾', array['#2e2415','#7a5f2d']),
('Dokdo Toner','Round Lab','toner','toner',119000,70000,30,'200 ml',
 'Minerallarga boy, sezgir teriga xavfsiz kundalik toner.',
 'Har yuvinishdan keyin qo''llang. Sezgir teri uchun ham mos.',
 'Ulleungdo chuqur dengiz suvi (72 mineral), HATCHING EX-07 fermenti',
 array['mineral','ferment'], array['sezgirlik','quruqlik'], array['sezgir','quruq','normal'],'🌊', array['#12222e','#2d5f7a']),
('Supple Preparation Facial Toner','Klairs','toner','toner',132000,78000,20,'180 ml',
 'Quruq va sezgir teri uchun klassik namlantiruvchi toner.',
 'Qatlam-qatlam (2-3 marta) yuzga singdiring.',
 'Beta-glyukan, gialuron kislotasi, Centella Asiatica, lipid kompleksi',
 array['beta-glyukan','centella','gialuron'], array['quruqlik','sezgirlik','qizarish'], array['quruq','sezgir'],'💜', array['#221a2e','#6b3d8a']),
-- ---------- SERUM ----------
('Snail 96 Mucin Power Essence','COSRX','serum','davolash',145000,86000,30,'100 ml',
 'Terini tiklaydi, aknedan keyingi izlarni tekislaydi, namlikni ushlaydi.',
 'Tonerdan keyin 1-2 tomchi olib butun yuzga yoying.',
 '96.3% shilliqqurt mutsini filtrati, gialuron kislotasi, allantoin',
 array['mutsin','gialuron','allantoin'], array['dog','quruqlik','ajin'], array['barcha','quruq','aralash'],'🐌', array['#2e2a1a','#8a7a3d']),
('Vitamin C 23 Serum','Klairs','serum','davolash',155000,92000,15,'20 g',
 'Yuqori konsentratsiyali C vitamini — dog'' va xiralikka qarshi kuchli vosita.',
 'Faqat kechqurun surting. Kunduzi albatta SPF ishlating. Sezgir teri sekin boshlasin.',
 'Toza vitamin C 23%, E vitamini, pantenol, allantoin',
 array['vitamin c','vitamin e'], array['dog','xiralik'], array['normal','yogli','aralash'],'🍊', array['#2e1c12','#b3641f']),
('Niacinamide 10% + Zinc 1%','Beauty of Joseon','serum','davolash',118000,70000,30,'30 ml',
 'Teshiklarni toraytiradi, yog'' ishlab chiqarishni muvozanatlaydi.',
 'Ertalab yoki kechqurun 2-3 tomchi surting.',
 'Propolis ekstrakti 60%, niatsinamid 2%, tamanu yog''i',
 array['niatsinamid','sink','propolis'], array['teshik','yoglilik','akne','dog'], array['yogli','aralash'],'🤍', array['#1e2226','#5c6b7a']),
('Ginseng Essence Water','Beauty of Joseon','serum','davolash',148000,88000,20,'150 ml',
 'Jenshen bilan qarishga qarshi essensiya, teri tonusini ko''taradi.',
 'Tonerdan keyin yuzga singdiring, so''ng krem qo''llang.',
 'Jenshen ildizi suvi 80%, niatsinamid 2%, adenozin',
 array['jenshen','adenozin','niatsinamid'], array['ajin','quruqlik','xiralik'], array['quruq','normal'],'🫚', array['#2a1c14','#8a5a3d']),
('Green Tea Seed Serum','Innisfree','serum','davolash',139000,82000,20,'80 ml',
 'Yengil, yopishmaydigan namlantiruvchi serum.',
 'Yuvinishdan so''ng darhol, nam teriga qo''llang.',
 'Green Tea Tri-biotics, Jeju yashil choy urug''i moyi, skvalan',
 array['yashil choy','skvalan'], array['quruqlik','yoglilik'], array['yogli','aralash','normal'],'🍃', array['#102a18','#2d8a4f']),
('Hyaluronic Acid Hydra Serum','Purito','serum','davolash',142000,84000,20,'60 ml',
 'Chuqur namlantiruvchi gialuron serumi, sezgir teriga xavfsiz.',
 'NAM teriga 2 tomchi surtib, darhol ustidan krem qo''llang.',
 'Gialuron kislotasi 90%, vitamin C, ko''k choy ekstrakti',
 array['gialuron','vitamin c'], array['quruqlik','sezgirlik'], array['quruq','sezgir','normal'],'💧', array['#12202e','#3d6b9a']),
-- ---------- KREM ----------
('Water Sleeping Mask EX','Laneige','krem','namlash',185000,110000,15,'70 ml',
 'Tungi namlovchi niqob — ertalab teri to''q va yumshoq bo''ladi.',
 'Kechqurun oxirgi bosqichda qalin qatlam qilib surting, ertalab yuving.',
 'Sleeping Micro-biome, probiotiklar kompleksi, skvalan',
 array['probiotik','skvalan'], array['quruqlik','xiralik'], array['quruq','normal','aralash'],'🌙', array['#141a30','#3d4f9a']),
('Moisturizing Cream Deep Type','Pyunkang Yul','krem','namlash',138000,82000,25,'100 ml',
 'Juda quruq va qipiqlangan teri uchun qalin tiklovchi krem.',
 'Ertalab-kechqurun oxirgi bosqichda surting.',
 'Astragalus Membranaceus ildiz ekstrakti, shea yog''i, makadamiya moyi',
 array['shea','makadamiya'], array['quruqlik','sezgirlik'], array['quruq','sezgir'],'🤎', array['#261a12','#7a4f2d']),
('Aloe Soothing Gel','Nature Republic','krem','namlash',65000,36000,40,'300 ml',
 'Qizarish va kuyishni tinchlantiruvchi aloe geli. Yuz va tanaga.',
 'Quyoshdan keyin, qizarish va qichishishda erkin surting.',
 '92% Kaliforniya tabiiy aloe vera ekstrakti, gialuron kislotasi',
 array['aloe','gialuron'], array['qizarish','sezgirlik','quruqlik'], array['barcha','sezgir','yogli'],'🌵', array['#12301a','#3d9a5a']),
('Snail Repair Eye Cream','Mizon','krem','namlash',125000,74000,20,'25 ml',
 'Ko''z atrofidagi ajin va qora doiralar uchun konsentrlangan krem.',
 'Ko''z atrofiga barmoq uchi bilan nuqta qo''yib, urib singdiring.',
 '80% shilliqqurt mutsini, EGF, peptidlar',
 array['mutsin','peptid','egf'], array['ajin','quruqlik','dog'], array['barcha','quruq','normal'],'👁️', array['#221e2e','#5a4f7a']),
('Birch Juice Moisturizing Cream','Round Lab','krem','namlash',149000,88000,20,'80 ml',
 'Yengil, lekin uzoq namlik beruvchi krem — barcha teri turlariga.',
 'Serumdan keyin oxirgi bosqichda surting.',
 'Inje qayin sharbati, Vita Hyaluronic Acid',
 array['qayin','gialuron'], array['quruqlik','sezgirlik'], array['barcha','quruq','normal'],'🌳', array['#1a2418','#4f6b3d']),
-- ---------- NIQOB ----------
('N.M.F Aquaring Mask (10 dona)','Mediheal','niqob','qoshimcha',95000,55000,30,'10 x 27 ml',
 'Tez namlantiruvchi mato niqob — muhim kunlar oldidan ideal.',
 'Tozalangan yuzga 15-20 daqiqa qo''ying, qolgan mohiyatni singdiring.',
 'N.M.F (tabiiy namlantiruvchi omil), gialuron kislota, seramidlar',
 array['nmf','seramid','gialuron'], array['quruqlik','xiralik'], array['barcha','quruq'],'🎭', array['#12222e','#2d6b8a']),
('Real Nature Mask Set (10 dona)','The Face Shop','niqob','qoshimcha',88000,50000,30,'10 x 20 g',
 'Turli ekstraktli mato niqoblar to''plami — haftalik parvarish uchun.',
 'Haftasiga 2-3 marta 15 daqiqadan qo''llang.',
 'Tabiiy meva va o''simlik ekstraktlari (Aloe, Anor, Guruch va h.k.)',
 array['ekstrakt'], array['quruqlik','xiralik','sezgirlik'], array['barcha','normal'],'🌸', array['#2e1a22','#8a3d5a']),
('Super Volcanic Clay Mask','Innisfree','niqob','qoshimcha',105000,62000,25,'100 ml',
 'Vulqon kuli bilan teshiklarni tozalovchi loy niqob.',
 'Haftasiga 1 marta quruq yuzga surtib, 10 daqiqadan so''ng iliq suvda yuving.',
 'Jeju vulqon kuli klasterlari, AHA kislota, minerallar',
 array['vulqon kuli','aha'], array['teshik','yoglilik','akne'], array['yogli','aralash'],'🌋', array['#241e1a','#6b4f3d']),
-- ---------- QUYOSH ----------
('Relief Sun Rice+Probiotics SPF50+','Beauty of Joseon','quyosh','himoya',135000,80000,40,'50 ml',
 'Oq iz qoldirmaydigan, yengil kundalik quyosh kremi. Eng ko''p sotiladigan SPF.',
 'Ko''chaga chiqishdan 20 daqiqa oldin surting, har 3 soatda yangilang.',
 'Guruch ekstrakti 30%, fermentlangan don probiotiklari',
 array['spf50','guruch','probiotik'], array['quyosh','dog','ajin'], array['barcha','quruq','normal'],'☀️', array['#2e2612','#b3941f']),
('Birch Juice Moisturizing Sunscreen SPF50+','Round Lab','quyosh','himoya',139000,82000,30,'50 ml',
 'Namlantiruvchi SPF — quruq teri uchun krem o''rnini ham bosadi.',
 'Kunduzi oxirgi bosqichda qo''llang.',
 'Qayin sharbati, gialuron kislotasi, DPG tinchlantiruvchi modda',
 array['spf50','qayin','gialuron'], array['quyosh','quruqlik','sezgirlik'], array['barcha','sezgir','quruq'],'🛡️', array['#12222e','#3d5f8a']),
-- ---------- LAB ----------
('Lip Sleeping Mask Berry','Laneige','lab','qoshimcha',115000,68000,25,'20 g',
 'Tungi lab niqobi — ertalab lab yumshoq va po''st tashlamaydi.',
 'Uxlashdan oldin labga qalin surting, ertalab o''lik terini muloyim artib oling.',
 'Berry Fruit Complex (vitamin C va antioksidantlar), kokos moyi',
 array['vitamin c','kokos'], array['quruqlik'], array['barcha'],'🍓', array['#2e1220','#9a2d5a']),
-- ---------- TO'PLAM ----------
('Soonjung pH 5.5 Barrier Kit','Etude House','toplam','qoshimcha',165000,98000,15,'4 ta mini vosita',
 'Sezgir terini tiklovchi to''liq mini to''plam. Sayohat va sinov uchun.',
 'Toner - essensiya - krem - niqob tartibida qo''llang.',
 'Panthenol + Madecassoside, gipoallergen formula',
 array['pantenol','madekassosid'], array['sezgirlik','qizarish','quruqlik'], array['sezgir','quruq'],'🎁', array['#1e2226','#4f5c6b'])
) as v(name, brand, cat, step, price, cost_price, stock, volume,
       description, usage_text, ingredients, actives, concerns, skin_types, emoji, gradient)
join public.categories c on c.slug = v.cat
on conflict (coalesce(brand, ''), name) do nothing;
